- name: populate inventory
  add_host:
    name: "{{ item.name }}"
    groups: "{{ item.grp }}"
    ansible_host: "{{ item.name }}.{{ lookup('env', 'DEMO_PREFIX') }}.{{ lookup('env', 'AWS_R53_DOMAIN') }}"
    ansible_ssh_private_key_file: '/data/id_rsa'
    ansible_user: ec2-user
  loop: "{{ inventory_hosts }}"
  loop_control:
    label: "{{ item.name }}"
  changed_when: no
  tags:
    - inventory
